- hosts: hosts
  become: yes

  tasks:
  - name: install git
    ansible.builtin.apt:
      name: git
      state: present

  - name: clone git
    ansible.builtin.git:
      repo: https://github.com/iphilka/stud-template.git
      dest: /home/ansible-worker/www/stud-template/
      clone: yes
      update: no
